### ISSUE TITLE
Peer Review from Chloe Ouyang

### ISSUE THREAD

**Issue by chloeouyang** [Kevinlyk2000/Project#4]
Content: 1) The purple color of the paragraph seems too fancy compared with the style of the menu bar. 2) The width of the paragraph seems too large.

Technical: 1) Setting border-collapse: collapse for the table CSS style on the home page may be better. 2) Organizing the paragraphs in the content pages using a table and setting it centered with a margin on both the left side and the right side may be better.

**Comment by Kevinlyk2000** [comment]
Thank you for your feedback! The color and table border issues have been tackled with in the final version.
